disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Emil Pawlak"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "02.01.2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  # buymeacoffee.globalWidget = true

[params.author]
  name = "Emil Pawlak"
  email = "EmilPawlak@protonmail.com"
  image = "img/author.jpg"
  imageQuality = 96
  headline = "Live each day as if it's your first."
  bio = "Aspiring Pentester | SOC Analyst | Web Developer"
  links = [
    { email = "mailto:EmilPawlak@protonmail.com" },
    { hackthebox = "https://profile.hackthebox.com/profile/019d3b64-1d14-7228-b18e-ae6966f25023" },
    { linkedin = "https://www.linkedin.com/in/emil-pawlak" },
    { youtube = "https://youtube.com/username" },
    { github = "https://github.com/EmilPawlak" },
    { buymeacoffee = "buymeacoffee.com/Azaeir" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { keyoxide = "https://keyoxide.org/URI" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { matrix = "https://matrix.to/#/URI" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { signal = "https://signal.me/#eu/userid" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
#     { printables = "https://www.printables.com/@username"},
  ]
